development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 500

production:
  adapter: postgresql
  encoding: unicode
  database: d98g2qgiqr536r
  pool: 5
  username: ygphlyeiqokjzo
  password: f31xsN0hGRMtNwp6k2YsY4JLYu

cucumber:
  <<: *test
